### ISSUE TITLE
How to remove appollo ？

### ISSUE THREAD

**Issue by walter211** [ksivamuthu/demo-graphql-nestjs#2]
Cause the official site is blocked by GFW …

**Comment by ksivamuthu** [comment]
If you don't want to use Apollo graphql engine, remove this line. You don't need to get the API key for engine then. 

https://github.com/ksivamuthu/demo-graphql-nestjs/blob/master/conference-graphql-api/src/app.module.ts#L18-L20

**Comment by walter211** [comment]
thx, pls close this issue
